name: Update Blood Levels Card

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update-blood-levels:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest tests/

    - name: Run Python script
      run: |
        python fetch_blood.py

    - name: Commit and push changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add README.md
        if ! git diff --staged --quiet; then
          git commit -m "Update blood levels card in README.md"
          git push
        else
          echo "No changes in blood levels detected."
        fi
